feat: TimeField component
kobaltedev/kobalte pull request #529
Opened 2024-11-16 16:36 UTC by HBS999

This PR adds a new TimeField component.

Closes #317

2024-11-17 15:39 UTC, HBS999 commented
I dont see how the failed tests are related to this PR.

2024-11-18 22:52 UTC, jer3m01 requested changes
Thanks for the PR, mostly looks good!

Small changes required;

The time zone segment shouldn't be interactive since we can change it.
![image](https://github.com/user-attachments/assets/50ab3fbd-09fc-4f8f-b6f9-96c9e11e1359)
`AM` should be the last highlighted item when you move right.

For arrow interaction the min and max should probably not inc/decrement when out of bounds. The warning should only appear if an invalid time is manually typed.
![image](https://github.com/user-attachments/assets/08516ac1-0b95-4551-a0f0-a69b4d01b93d)

Placeholder doesn't seem to work (W11 FF 132.0.2):
![image](https://github.com/user-attachments/assets/91502836-a28d-4739-841e-46761473e8ff)

Lastly the hidden input should follow changes to it, this is done to allow browser form autofill and cache. More info below.

2024-11-18 22:52 UTC, jer3m01 commented on packages/core/src/time-field/time-field-hidden-input.tsx
> +			hidden
This should use `style={visuallyHiddenStyles}` instead, this is still recognized as visible by browsers but doesn't actually show. Should also be aria-hidden.

2024-11-18 22:52 UTC, jer3m01 commented on packages/core/src/time-field/time-field-hidden-input.tsx
> +		/>
`onChange` is needed here, while not used by users, browsers will recognize the field and autofill or cache the value when you refresh the form.

`onChange` should parse the text value and update `context.setValue(...)`.

2024-11-18 23:08 UTC, jer3m01 commented
> When you increment the hour, it doesn’t start at 9?

Yeah it does, I still think it would be good to also make it display the placeholder in gray (and become a value on first interact).

2025-02-22 00:33 UTC, jer3m01 approved these changes
Looks great, thanks for the changes!

2025-07-26 23:45 UTC, merged